### ISSUE TITLE
Feature request: per frame + points/bbox annotation at the same time

### ISSUE THREAD

**Issue by DanFu09** [kayvonf/klabel#2]
Want to be able to make per-frame annotations (with keys) and make annotations on the frame at the same time. The use case is that we need to annotate location of contact on contact frames - but we don't always want to have to click (the ball location is often correct and will give it to us for free).

**Comment by kayvonf** [comment]
Done.  You can now set the keypress labeling mode (NONE, PER_FRAME_CATEGORY) and the mouse click labeling model (NONE, EXTREME_POINTS_BBOX, REGULAR_BBOX, POINT) independently.  This allows for a keypress labeling model to be active at the same time as a click labeling mode.

You now need to set both the keypress labeling mode (DEFAULT=NONE) and the click labeling mode. (DEFAULT= EXTREME_POINTS_BBOX)

See usage example here:
https://github.com/kayvonf/klabel/blob/72b76e5099b6550de390852affb122dea87c9756/labeler.html#L352
